### ISSUE TITLE
Docker for Windows Issue

### ISSUE THREAD

**Issue by SeidChr** [Graylog2/documentation#86]
Hi,

i graylog seems to have issues when running in docker for windws (hyperv vm). following errors occure as soon as i open the webinterface:

```
graylog_1        | 2016-06-08 14:03:37,111 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://docker.local:12900/system/metrics/multiple on node <8055968d-b53e-46c7-8153-ff9810633a27>, caught exception: docker.local (class java.net.UnknownHostException)
graylog_1        | 2016-06-08 14:03:39,113 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://docker.local:12900/system/metrics/multiple on node <8055968d-b53e-46c7-8153-ff9810633a27>, caught exception: docker.local (class java.net.UnknownHostException)
graylog_1        | 2016-06-08 14:03:41,235 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://docker.local:12900/system/metrics/multiple on node <8055968d-b53e-46c7-8153-ff9810633a27>, caught exception: docker.local: unknown error (class java.net.UnknownHostException)
graylog_1        | 2016-06-08 14:03:43,122 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://docker.local:12900/system/metrics/multiple on node <8055968d-b53e-46c7-8153-ff9810633a27>, caught exception: docker.local (class java.net.UnknownHostException)
graylog_1        | 2016-06-08 14:03:45,105 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://docker.local:12900/system/metrics/multiple on node <8055968d-b53e-46c7-8153-ff9810633a27>, caught exception: docker.local (class java.net.UnknownHostException)
graylog_1        | 2016-06-08 14:03:47,125 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://docker.local:12900/system/metrics/multiple on node <8055968d-b53e-46c7-8153-ff9810633a27>, caught exception: docker.local (class java.net.UnknownHostException)
graylog_1        | 2016-06-08 14:03:49,109 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://docker.local:12900/system/metrics/multiple on node <8055968d-b53e-46c7-8153-ff9810633a27>, caught exception: docker.local (class java.net.UnknownHostException)
```

the docker-compose file i am using:

```
mongo:
  image: "mongo:3"
elasticsearch:
  image: "elasticsearch:2"
  command: "elasticsearch -Des.cluster.name='graylog'"
graylog:
  image: graylog2/server:2.0.0-1
  environment:
    GRAYLOG_PASSWORD_SECRET: somepasswordpepper
    GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    GRAYLOG_REST_TRANSPORT_URI: http://docker.local:12900
  links:
    - mongo
    - elasticsearch
  ports:
    - "9000:9000"
    - "12900:12900"
    - "5555:5555/udp"
```

The site in general is running, but it seems that i cannot successfully add inputs.
Was looking through several bug forums, and as far as i could find out, the `GRAYLOG_REST_TRANSPORT_URI: http://docker.local:12900` must be a url the browser can access (which it is...)
